#!/bin/sh
#
# Install Sensu Client
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/sensu
CONFIG_DIR=/etc/sensu
PREFIX="/usr"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

ln -sf $DEST_DIR/bin/sensu-client $PREFIX/bin || error_exit "Cannot link sensu-client to $PREFIX/bin"
ln -sf $DEST_DIR/bin/sensu-api $PREFIX/bin || error_exit "Cannot link sensu-api to $PREFIX/bin"
ln -sf $DEST_DIR/bin/sensu-server $PREFIX/bin || error_exit "Cannot link sensu-server to $PREFIX/bin"

echo "Thank you for installing Sensu!"

exit 0
